module.exports={
        devServe:{
                proxy:{
                        '/user':{
                                target:'http://127.0.0.1:7001'
                        }
                }
        }
}